### PR TITLE
Update to gitlab 8.6

### PR DESCRIPTION
**Pull request by Gomez**
Tested on my prod system.

### CODE REVIEW

**Comment by drybjed** [comment]
I think that issue is on the Ansible side, I've asked the developers, awaiting response.

**Comment by benalbrecht** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/update/8.5-to-8.6.md#6-updates-for-postgresql-users
This will probably not work on postgres due to the missing pg_trgm extension.
I might do a PR after 8.7 is released.

**Comment by drybjed** [comment]
Yeah, saw that. The `debops.postgresql_server` would need to gain support for plugin management, not sure yet how it's done in PostgreSQL. I imagine that some plugins could be enabled by default to make things easier, `pg_trgm` being one of them. There's no good way to do it directly in `debops.gitlab` role, unfortunately.

**Comment by benalbrecht** [comment]
this module should help: https://docs.ansible.com/ansible/postgresql_ext_module.html

`postgresql-contrib` is already installed by default: https://github.com/debops/ansible-postgresql_server/blob/master/defaults/main.yml#L23

**Pull request merged**
