### PR TITLE
Add support for Gitlab 10.0.

### PR DESCRIPTION
**Pull request by bfabio**

### CODE REVIEW

**Comment by drybjed** [comment]
@bfabio I tried this PR on existing GitLab 9.4 installation (merge conflict is easily solvable). Unfortunately, there are still migration issues, and from [this post on GitLab blog about 10.0.3 release](https://about.gitlab.com/2017/10/05/gitlab-10-dot-0-dot-3-released/) it seems that 10.x will have some issues for a while.

Are the changes in the configuration file relevant to 9.4 release? This one seems to be stable right now, and I think that we should stick with it for a bit. If you think that the changes apart from the version bump are relevant, maybe you could include them in a separate PR? Otherwise I would prefer to tag the current `master` branch of the role as the next release and postpone further changes and GitLab version bump to after the repository merge, unless the migration issues are fixed by GitLab team.

**Comment by drybjed** [comment]
Interesting, [this issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/38222) suggests that GitLab 10 does not support PostgreSQL 10. I'll try testing this PR tommorow with PostgreSQL from Debian Stretch then.

**Comment by drybjed** [comment]
OK, got some progress - the role passes the migration task with PostgreSQL 9.6 from Debian Stretch, but fails again at asset compilation due to [a Yarn bug](https://gitlab.com/gitlab-org/gitlab-ce/issues/38457). I'll try to move the test on Travis to this point, but I still don't see this PR merged in yet. So, are the changes in the configuration files relevant to the GitLab 9.4 version?

**Comment by bfabio** [comment]
> from this post on GitLab blog about 10.0.3 release it seems that 10.x will have some issues for a while.

What do you mean? Those are issues fixed with that point release, much like the 9.x series.

> Are the changes in the configuration file relevant to 9.4 release?

Yes, they are. We were a little behind compared with the example `gitlab.yml`, it shouldn't be a big deal and 9.4 should work just fine, but still.

**Comment by drybjed** [comment]
I meant that even with these issues fixed there are still more, even on a clean install, so I expect a few more releases.

OK, I'll try adding the configuration changes in a separate PR, and then release the role with GitLab 9.4 for now. Thanks for the clarification.

**Comment by bfabio** [comment]
> Interesting, this issue suggests that GitLab 10 does not support PostgreSQL 10.



> OK, got some progress - the role passes the migration task with PostgreSQL 9.6 from Debian Stretch, but fails again at asset compilation due to a Yarn bug

This is odd, that bug report mentions the bug is in versions prior to 1.0.x, but we should install 1.2.0 from https://dl.yarnpkg.com/debian/.

**Comment by drybjed** [comment]
@bfabio Correct, `yarn` 1.2.0 from the APT repository is installed on my test host. Here's the task output with the error:
```
TASK [debops.gitlab : Precompile GitLab assets] ************************************************************************************************
fatal: [first]: FAILED! => {"changed": true, "cmd": ["bundle", "exec", "rake", "gitlab:assets:compile", "RAILS_ENV=production", "NODE_ENV=produc
tion"], "delta": "0:00:22.111399", "end": "2017-10-10 10:07:08.244486", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-1
0-10 10:06:46.133087", "stderr": "warning \"minimatch#brace-expansion@^1.0.0\" could be deduped from \"1.1.8\" to \"brace-expansion@1.1.8\"\nerr
or \"webpack#ajv\" not installed\nerror \"webpack#ajv-keywords\" not installed\nerror Found 2 errors.\nError: You have unmet dependencies. (`yar
n check` command failed)\nRun `yarn install` to install missing modules.", "stderr_lines": ["warning \"minimatch#brace-expansion@^1.0.0\" could 
be deduped from \"1.1.8\" to \"brace-expansion@1.1.8\"", "error \"webpack#ajv\" not installed", "error \"webpack#ajv-keywords\" not installed", 
"error Found 2 errors.", "Error: You have unmet dependencies. (`yarn check` command failed)", "Run `yarn install` to install missing modules."],
 "stdout": "", "stdout_lines": []}
```

**Comment by bfabio** [comment]
[This](https://gitlab.com/gitlab-org/gitlab-ce/commit/999e979a017d5ae852d4202deb3798f582273fb5) should fix it, but it doesn't come with GitLab 10.0.3. I guess 10.0.4 will include it.

**Comment by drybjed** [comment]
GitLab 10.0.4 was released a few days ago but it looks like the bug that affects us, at least in the Travis-CI environment, is still there. I would like to do the project repository merge during the weekend, therefore I'm closing this PR for now. @bfabio, if you want, you could try creating a new PR without the GitLab update to 10.x, ie. only with the configuration file changes. If that passes, I can merge it in tommorow before starting the migration. Otherwise, we can get back to it after migration is done.

**Comment by alinalexandru** [comment]
Any status update on this?
I would like to add support for 10.1 or 10.2

**Comment by drybjed** [comment]
No, I haven't checked newer versions of GitLab yet, sorry.

The current version of GitLab in the DebOps monorepo installs correctly on Debian Stretch LXC container in my test environment (still working on it). You can fork the monorepo and add your changes, then create a new PR. I'll test it out and merge if it works.

**Pull request closed without merging**
