### PR TITLE
add support for gitlab 8.5

### PR DESCRIPTION
**Pull request by benalbrecht**

### CODE REVIEW

**Comment by drybjed** [comment]
@benalbrecht Nice work, let's see if it passes on Travis. :-)

**Comment by drybjed** [comment]
It looks like GitLab itself hasn't been configured, the [tasks aren't included](https://travis-ci.org/debops/ansible-gitlab/builds/112243375#L1829). Not sure why yet, I'll try this PR on my own host when I get the chance.

**Comment by benalbrecht** [comment]
ah, i only tested it on ansible 1.9, that might be an issue with ansible 2.0

**Comment by drybjed** [comment]
@benalbrecht I've tried your branch on one of my developent servers, looks like an upgrade from GitLab 8.1 to 8.5 went fine (haven't tested all functions though). I'll try installing a clean instance next. One problem I noticed during the upgrade was that a deploy HTML page wasn't showing up, not sure about that.

I'll try to find out why Travis doesn't want to pass next.

**Comment by drybjed** [comment]
@benalbrecht Currently Travis-CI build is stuck on [this step](https://travis-ci.org/debops/ansible-gitlab/builds/112243375#L2225), build of `gitlab-workhorse` which of course is written in Go. No idea how to make Travis-CI build it yet...

**Comment by drybjed** [comment]
The test environment is now fixed, although Ansible `devel` was required to make the test work. It looks like current Ansible stable release [does not run included files](https://github.com/ansible/ansible/issues/14727). Since the test passes, I'm going to merge this PR anyway and clean it up/tag the release later.

**Pull request merged**
