### PR TITLE
Update to gitlab version 8.11 (including version info for 8.10).

### PR DESCRIPTION
**Pull request by anzil**

### CODE REVIEW

**Comment by drybjed** [comment]
Interesting. :-) @anzil, have you tested if both versions work correctly?

**Comment by anzil** [comment]
Yes, both versions work. So far, no problems discovered.

**Comment by Gomez** [comment]
The workhores version should be 0.7.11, see this link to 811-stable:
https://github.com/gitlabhq/gitlabhq/blob/8-11-stable/GITLAB_WORKHORSE_VERSION

I just used my PR https://github.com/debops/ansible-gitlab/pull/53 successful on production (with workhores 0.7.11). After updating to 0.7.11 its ready to merge.

**Comment by drybjed** [comment]
I'll wait with mering the other PRs to not jinx the `git` tree. @anzil , can you update the PR with the correct workhorse version?

**Pull request merged**
