### PR TITLE
always create pages and add gitaly service

### PR DESCRIPTION
**Pull request by cultcom**
the pages directory is required for the rake backup task which failed on my setup when the directory was not present.

A first template and conditionally added service file for gitaly which will be available from 9.0 onwards

### CODE REVIEW

**Comment by drybjed** [comment]
It looks like the issues with `bundler` are known and should be fixed in GitLab master branch (ref: [gitlab issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/32653), [github issue](https://github.com/bundler/bundler/issues/5697). I'm not sure if the fix will be backported to older release branches.

**Comment by cultcom** [comment]
no, the backup job had a different problem. It tried to backup files in .../shared/pages and failed with "no such directory"

**Comment by drybjed** [comment]
@cultcom Sure, I'm talking about current issue with Travis not able to finish gem installation.

**Comment by cultcom** [comment]
this is going to be part of the 9.x changes.

**Pull request closed without merging**
