### PR TITLE
Add support for GitLab 9.5.

### PR DESCRIPTION
**Pull request by bfabio**

### CODE REVIEW

**Comment by drybjed** [comment]
@bfabio It looks like the error is due to the old PostgreSQL on Ubuntu Precise. I switched Travis to use Ubuntu Trusty, can you rebase this PR, fix conflicts in the Changelog and push the changes to see if this will fix the build errors?

**Comment by bfabio** [comment]
@drybjed Done, it looks like there is still a PostgreSQL related issue.

**Comment by drybjed** [comment]
I just checked to be sure and both tests (for 9.5 and for 10.0) use the same PostgreSQL database version. I suspect that the issue is in the GitLab 9.5 code somewhere, I tried googling for the error but not much luck...

I think that we could skip the 9.5 support altogether and go with 10.0 directly, although I will first test if migration from 9.4 works... @bfabio, could you copy the additional changes in the config files from this PR to the 10.0 one?

**Comment by bfabio** [comment]
Pushed to https://github.com/debops/ansible-gitlab/pull/99

**Pull request closed without merging**
