### PR TITLE
Rework 5

### PR DESCRIPTION
**Pull request by ypid**
Starting with 10.1 OpenPGP verification will probably become usable: https://gitlab.com/gitlab-org/gitlab-ce/issues/36829 Nice stuff :)

### CODE REVIEW

**Comment by ypid** [comment]
@drybjed You can check it out if you want. I did not further investigate the build issues.

**Comment by drybjed** [comment]
@ypid, it seems that `gitlab-workhorse` cannot be built in the current Travis-CI environment. I tried to [build it manually in the test environment](https://github.com/debops/test-suite/blob/master/ansible-gitlab/test#L85-L99), but it fails there as well. I guess something is missing, not sure what yet. I'll look at it further a bit later.

**Comment by ypid** [comment]
Thanks! Note that the move of the `include: configure_gitlab_ce.yml` is not fully tested by me.

**Comment by drybjed** [comment]
@ypid Can you fix the merge conflicts with the current role and update the PR? It will be tested on Ubuntu Trusty now.

**Comment by ypid** [comment]
Sure, updated.

**Comment by drybjed** [comment]
@ypid Thanks for rebasing. I tested this PR on a clean Debian Stretch and both times `gitlab-gitaly.service` did not start correctly initially; it started fine after a reboot. I'm guessing that since `gitlab.slice` is started before `gitlab-gitaly.service` is created, there might be some issues.

I'll try and move the start steps to a new file executed after gitaly setup, perhaps this will help.

**Comment by ypid** [comment]
@drybjed Thanks for checking.

**Pull request merged**
