### PR TITLE
Update PostgreSQL support, redesign role dependencies

### PR DESCRIPTION
**Pull request by drybjed**

### CODE REVIEW

**Comment by drybjed** [comment]
Requesting review from @bfabio, @Gomez and @cultcom as frequent users of DebOps GitLab role.

**Comment by bfabio** [comment]
@drybjed LGTM, great job! Gonna test a deploy next week.

**Comment by stefangweichinger** [comment]
Applied to existing gitlab-8.16-installation, upgrade ran through without problems, now at 8.17.
thanks!

**Comment by bfabio** [comment]
@drybjed Works here too.

**Pull request merged**
