### PR TITLE
Upgrade to 8.7 and pg_trgm extension support

### PR DESCRIPTION
**Pull request by benalbrecht**

### CODE REVIEW

**Comment by drybjed** [comment]
Well, this is unorthodox. :-) I haven' worked with PG extensions yet, can they be enabled/disabled in the database by any user or do you need admin privileges?

**Comment by benalbrecht** [comment]
they need admin privileges, that's why `postgresql_ext` executes as `ansible_local[gitlab_database].user`

**Comment by drybjed** [comment]
Well, I guess it's fine to merge right now, since `debops.postgresql` doesn' support extension management for now... Did you try it with a PostgreSQL server on another host?

**Comment by benalbrecht** [comment]
yup, works fine. i have gitlab and postgresql running in separate lxc containers.

**Comment by drybjed** [comment]
OK then, I'm gonna merge this, thanks! I'd still prefer the extension management to be either in `debops.postgresql` if the extensions are on database-level though. That can come later when this is implemented.

**Pull request merged**
